name: vignettenoir
favicon: null
layout_spectrum: 0.8443900188431144
typography_spectrum: 0.5187393350061029
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1311276452615857
  lightness: 0.07800826709717512
  saturation: 0.3841065391898155
  rhythmicContrast: 0.5757727555464953
purpose: []
