color:
  brandStrength: 0.1311276452615857
  saturation: 0.625
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.875
  rhythmicContrast: 0.5757727555464953
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.8443900188431144
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
name: vignettenoir
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5187393350061029
