name: vignettenoir
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4012
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bebebe'
    - '#7f7f7f'
    - '#2f2f2f'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
